files:
  - source: /lang/en/*.php
    translation: /lang/%two_letters_code%/%original_file_name%
    ignore:
      - /lang/**/actions.php
      - /lang/**/auth.php
      - /lang/**/http-statuses.php
      - /lang/**/pagination.php
      - /lang/**/passwords.php
      - /lang/**/validation.php
